AllCops:
  Exclude:
    - 'src/libs/**/*'

Naming/MethodParameterName:
  Enabled: true
  AllowedNames:
    - dt
    - x
    - y
    - z

Metrics/ClassLength:
  Enabled: true
  Max: 150

Metrics/MethodLength:
  Enabled: true
  Max: 25

# AFAIK it doesn't have an effect on MRuby, neither
# I find it useful for me
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

# There's no english names in MRuby
Style/SpecialGlobalVars:
  Enabled: false
